django-blog/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>/", views.detail, name="detail"),
    path("<int:post_id>/comment/", views.comment, name="comment"),
]

django-blog/mysite/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls  # type: ignore
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path("", lambda request: redirect("blog/", permanent=False)),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
    *debug_toolbar_urls(),
]

django-blog/blog/models.py
import datetime

from django.db import models
from django.utils import timezone


class Post(models.Model):
    post_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField("publishing date")

    def __str__(self) -> str:
        return self.post_text

    def was_published_recently(self) -> bool:
        # this is a stupid method, but Django tutorial said that I should
        # add it
        #
        # ... and test it
        if self.pub_date > timezone.now():
            # no timetravelers here, please
            return False

        # one minute because, uhm, time flies
        #
        # so like, if we have a post that was published exactly day ago, by the
        # time Python goes to evaluate this expression, some seconds have passed
        # and this breaks tests
        #
        # shouldn't we fix the tests instead? well, maybe ...
        # but idk
        return timezone.now() - self.pub_date < datetime.timedelta(
            days=1, minutes=1
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("publishing date")

    def __str__(self) -> str:
        return self.comment_text

django-blog/blog/views.py
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import Post


# Create your views here.
def index(request) -> HttpResponse:
    # only show posts that already have been published
    # i. e. ones with pub_date less than or equal to 'now'
    #
    # p. s. that's the weirdest ORM syntax I've ever seen (not that I've seen
    # many)
    # p. p. s and of course, mypy can't catch any mistakes here, that sucks
    posts = Post.objects.filter(pub_date__lte=timezone.now()).order_by(
        "-pub_date"
    )
    context = {"post_list": posts}
    return render(request, "blog/index.html", context)


def detail(request, post_id: int) -> HttpResponse:
    p = get_object_or_404(Post, pk=post_id)
    return render(
        request,
        "blog/detail.html",
        {
            "post": p,
            "comments": p.comment_set.all(),
        },
    )


def comment(request, post_id) -> HttpResponse:
    p = get_object_or_404(Post, pk=post_id)
    # p. s. this could be pattern match (or if) on .get()
    try:
        comment = request.POST["comment"]
    except KeyError:
        return render(
            request,
            "blog/detail.html",
            {
                "post": p,
                "comments": p.comment_set.all(),
                # TODO(me): actually use this at some point
                "error": "we couldn't get your comment, sommry!",
            },
        )
    else:
        p.comment_set.create(comment_text=comment, pub_date=timezone.now())
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        #
        # ^ source: Django Docs, Tutorial part 4
        return HttpResponseRedirect(reverse("blog:detail", args=(post_id,)))

django-blog/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My Django blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'blog:index' %}"> * Blog</a>
    </header>
    {% block content %}{% endblock %}
    <footer>
        <pre>Made with Django &copy juliancoffee 2024</pre>
    </footer>
</body>
</html>

django-blog/blog/templates/blog/detail.html
{% extends "./base.html" %}

{% block content %}
<pre>{{ post.post_text }}</pre>
<span>
    <em> Written: {{ post.pub_date }} </em>
<span>
{% if comments %}
    <ul>
        {% for comment in comments %}
            <li>{{ comment.comment_text }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No comments yet 🐾</p>
{% endif %}
<form action="{% url 'blog:comment' post.id %}" method="POST">
{% csrf_token %}
    <input type="text" id="comment" name="comment">
    <input type="submit" value="Meow!">
</form>
{% endblock %}

django-blog/blog/templates/blog/index.html
{% extends "./base.html" %}

{% block content %}
{% if post_list %}
    <ul>
        {% for post in post_list %}
            <li>
                <a href="{% url 'blog:detail' post.id %}">
                    {{ post.post_text }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Nothing to see here. Yet 👀<p>
{% endif %}
{% endblock %}